# Generated by Django 2.1.3 on 2018-11-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaresponse',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
