# Generated by Django 2.1.3 on 2018-12-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0006_auto_20181129_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
