# Generated by Django 2.1.3 on 2018-12-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0007_triviaquestion_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
