# Generated by Django 2.1.3 on 2018-12-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0008_triviaquestion_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triviaquestion',
            old_name='published',
            new_name='publish',
        ),
    ]
