# Generated by Django 2.1.3 on 2018-12-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0009_auto_20181202_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviastats',
            name='player',
        ),
        migrations.DeleteModel(
            name='TriviaStats',
        ),
    ]
